server:
  port: 8891
logging:
  path: /tmp/clairvoyance

mysql:
  url: jdbc:mysql://127.0.0.1:3306/clairvoyance?useSSL=false&characterEncoding=UTF-8
  username: root
  password: root

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
